ETF_EXCLUDE = [
    # 마스터에는 있으나 실제로 검색해보니 ETF가 아닌 애들: History를 수집하지 않는다
    # Sorting 한 상태 유지하기
    'ABCS', 'AEMB', 'ALUM', 'AMJ', 'ASGI', 
    'BBIP', 'BECO', 'BGU', 'BHF', 'BHFAL', 
    'BHFAN', 'BHFAO', 'BHFAO', 'BHFAP', 'BKKCF', 
    'BNE', 'BNPC', 'BRIL', 'BSCB', 'BSCD', 
    'BSJC', 'BSJD', 'BTAH', 'BTEC', 'BTEK', 
    'BTHM',
    'CACG', 'CALY', 'CETF', 'CHAI', 'CLIA', 
    'CNFRL', 'COWL', 'CRBA', 'CRBI', 'CZI', 
    'DBCN', 'DBEH', 'DBGCF', 'DFHY', 'DFNV', 
    'DFRA', 'DIP', 'DTE', 'DTP', 
    'EATX', 'EBLU', 'EDOC', 'EFN', 'EFUT', 
    'EMER', 'EMFM', 'EMFQ', 'EMGX', 'EMSG', 
    'EMVX', 'ENBA', 'EQIN', 'ESGA', 'ESGB', 
    'ESGN', 'ESGS', 'ESGY', 'EWAC', 'EWEF', 
    'EWSM', 
    'FBGX', 'FBGXFCGS', 'FCGL', 'FHC', 'FIVG', 
    'FLG', 'FLLV', 'FLYX', 'FNGU', 'FOC', 
    'FUI', 'FXRU', 'FZB', 
    'GDEF', 'GDLC', 'GDVD', 'GERM', 'GHEE', 
    'GRPC', 'GXTG', 
    'HBTA', 'HDAW', 'HEWG', 'HJEN', 'HMTM', 
    'HTGC', 'HVOL', 'HYMU', 
    'IAUF', 'IHEMF', 'IMSI', 'INAV', 'INDZ', 
    'IRBO', 'ISDB', 'ISZE', 'IVES', 'IWFH', 
    'IWIN', 
    'JEPY', 'JYF', 
    'KDIV', 'KFVG', 'KLNE', 'KMET', 'KOIN', 
    'KRNIF', 'KRUZ', 
    'LGLBF', 'LSST', 'LWPE', 
    'MOHR', 'MOON', 
    'NBCT', 'NETZ', 'NUSI', 
    'OAIA', 'OAIB', 
    'PSEC', 'PTMN', 'PUTW', 
    'RGA', 'RNMC', 'RNSC', 'ROYA', 'RUFF', 
    'SFIG', 'SMDY', 'SMLE', 'SOF', 'SQY', 
    'SSLY', 'STLG', 'SYII', 'SYUS', 
    'TPVG', 'TRES', 'TSLH', 'TTAC', 'TTAI', 
    'USBF', 'USCF', 
    'VCAR', 'VMOT', 'VNMC', 
    'WFHY', 'WFIG', 'WPS', 
    'XXXX', 
    'ZIVB'
]